[build]
  base = "frontend/"
  publish = "build/"
  command = "npm run build"

[dev]
  command = "npm start"
  port = 3000

# Redirect all paths to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
